### ISSUE TITLE
Toy dataset can not be processed correctly.

### ISSUE THREAD

**Issue by elleryyu** [zhijian-yang/GeneSGAN#1]
Hi Zhijian,

When I tried to run your sample_code with toy_dataset, it alway return me as I shared. It seems that participant_id also get involved in calculation. How should I avoid this without deleting the corresponding column?
<img width="1555" alt="Screenshot 2024-04-22 at 9 40 42 PM" src="https://github.com/zhijian-yang/GeneSGAN/assets/97306768/efd01837-1ba5-425e-91c8-acacdc7eff0f">

**Comment by zhijian-yang** [comment]
Hi! This problem might be due to the difference in Pandas version. Please try changing your Pandas version to 1.5.3 in your virtual environment.

**Comment by elleryyu** [comment]
Thank you so much, the issue has been fixed. Thank you for your patience and your excellent work!
