### ISSUE TITLE
Issue happened while using my dataset. 

### ISSUE THREAD

**Issue by elleryyu** [zhijian-yang/GeneSGAN#2]
I have cleaned my dataset so that no null value at all entries. I am wondering what I should focus on to solve it, and here is the screenshot for the error. Appreciate!

<img width="1284" alt="Screenshot 2024-04-29 at 3 36 08 AM" src="https://github.com/zhijian-yang/GeneSGAN/assets/97306768/2fd0b793-8a8a-475b-b014-68b820195844">

**Comment by elleryyu** [comment]
And the input datasets' form are based on the toy project you provided

**Comment by elleryyu** [comment]
I just saw the cn is -1 other than 0 in default setting. sorry for the question

**Comment by elleryyu** [comment]
I am sorry, it seems that a new issue occurred. when I try to keep running the code, error occurred again. when the target_is_real, the prob did not match the new target var

<img width="1353" alt="Screenshot 2024-04-29 at 5 39 12 AM" src="https://github.com/zhijian-yang/GeneSGAN/assets/97306768/10da33de-cdca-4b68-a17f-cf4e65595426">

**Comment by zhijian-yang** [comment]
It seems that one possible reason is that your control sample size is 36, which is smaller than the batch size you set (probably 58 here?). Please try a batch size smaller than the control sample size and let me know if that is the case or not!

**Comment by elleryyu** [comment]
Thanks for your patience and this problem has fixed just as you mentioned.
